name: Setup MicroK8s with QEMU Emulating ppc64le

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  microk8s-setup:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU for ppc64le emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/ppc64le

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Enable QEMU emulation for ppc64le
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Install MicroK8s in emulated ppc64le environment
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install microk8s --classic

      - name: Enable MicroK8s Add-ons
        run: |
          sudo microk8s.enable dns storage

      - name: Wait for MicroK8s to be ready
        run: |
          sudo microk8s status --wait-ready

      - name: Test MicroK8s Cluster
        run: |
          sudo microk8s kubectl get nodes
          sudo microk8s kubectl run test-pod --image=nginx --restart=Never --dry-run=client -o yaml
          sudo microk8s kubectl get pods

